# Generated by Django 5.0 on 2024-01-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeid', models.IntegerField()),
                ('productid', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('commend', models.TextField()),
            ],
            options={
                'db_table': 'notes',
            },
        ),
    ]
