# Generated by Django 5.0 on 2024-01-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=11)),
                ('code', models.CharField(max_length=11)),
                ('nikname', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
