# Generated by Django 5.0.1 on 2024-01-24 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0004_registeruser"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="note",
            table="note",
        ),
    ]
