# Generated by Django 5.0.1 on 2024-01-24 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0005_alter_note_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="note",
            table="notes",
        ),
    ]
